language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=2.1.1
  - MRUBY_VERSION=master
matrix:
  allow_failures:
    - env: MRUBY_VERSION=master
branches:
  only:
    - master

before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git gperf libc6-dev
script:
  - rake clean
  - rake test
